---
title: "Buoy project"
author: "Yuelin Jiang"
date: "9/25/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("knitr","ggplot2","rstanarm","tidyverse","lubridate","astsa")
```

## Retrive data from the site [credit: Jason Huang]
This part is done by my teammate Jason Huang. I am starting my work based on the raw data "Buoy_MR.csv" generated by him.


## Clean Data


```{r}
# Read the raw data from csv file

buoy <- read.csv("Buoy_MR.csv")

# Only keep useful columns
buoy <- buoy %>% select(YYYY, MM, DD, hh, ATMP, WTMP)

# Only keep noon time (hh==12) data for warmest temperature
# Remove abnormal days where temperature is higher than 60 degrees.
buoy <- buoy %>% filter((hh == "12") & (ATMP <=60) & (WTMP <= 60))


# Get monthly average of air temp and water temp
atmp_avg <- buoy %>% 
  group_by(YYYY, MM ) %>%
  summarise(atmp = mean(ATMP))
 
wtmp_avg <- buoy %>%
  group_by(YYYY, MM) %>%
  summarise(wtmp = mean(WTMP))

# Combine atmp and wtmp into one dataframe
monthly <- inner_join(atmp_avg, wtmp_avg)  

monthly_time <- monthly %>% unite(monthly, YYYY, MM, sep = "-")


```

## Data analysis

```{r}
#plotting monthly average air tmp

plot.ts(monthly_time$atmp)

#plotting monthly average water tmp

plot.ts(monthly_time$wtmp)
```


```{r}

# Since there are seasonal fluctuations which made the overall trend hard to observe. So we plot each month separately.

 par(mfrow=c(3,4))

for (i in c(1:12)) {
 
 month_i <- filter(monthly, MM == i)
 x <- month_i$YYYY
 lm <- lm(atmp ~ x, data = month_i) 
 b <- coef(lm)
 print(b)
 if (b[2] > 0){
      plot(x = month_i$YYYY, y = month_i$atmp, xlab = "Year", ylab = "Air Temp",
           main = paste("Month_", i))
      abline(b[1], b[2], col="RED")
 }
 if (b[2]<0){
      plot(x = month_i$YYYY, y = month_i$atmp, xlab = "Year", ylab = "Air Temp",
           main = paste("Month_", i))
      abline(b[1], b[2], col="BLUE")
 }
}


```

# Repeat the same process with water temp

```{r}
par(mfrow=c(3,4))
for (i in c(1:12)) {
 
 month_i <- filter(monthly, MM == i)
 lm <- lm(wtmp ~ YYYY, data = month_i) 
 b <- coef(lm)
 print(b)
 if (b[2] > 0){
      plot(x = month_i$YYYY, y = month_i$wtmp, xlab = "Year", ylab = "Water Temp",
           main = paste("Month_", i))
      abline(b[1], b[2], col="RED")
 }
 if (b[2]<=0){
      plot(x = month_i$YYYY, y = month_i$atmp, xlab = "Year", ylab = "Water Temp",
           main = paste("Month_", i))
      abline(b[1], b[2], col="BLUE")
   
 }
}

```

Time series analysis

```{r}

ts_mon <- ts(select(monthly_time, atmp))
plot(ts_mon,type="b")

#set seasonal index
diff12 = diff(ts_mon,12)
plot(diff12,type="b")

sarima(ts_mon,12,0,0,0,1,1,12)
sarima.for(ts_mon,132,1,0,0,0,1,1,12)

```
```{r}
# Citations
citation()
citation("rstanarm")
citation("ggplot2")
citation("knitr")
citation("tidyverse")
citation("lubridate")
citation("astsa")
```

